version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: process_mapper_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: process_mapper_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: